### PR TITLE
Upgrade to Laravel Mix 6

### PR DESCRIPTION
**Pull request by Jubeki**

### CODE REVIEW

**Comment by stidges** [comment]
@Jubeki Thanks for this! Have you verified if this is working as expected on Laravel Mix v6? I don't have an active project on that version yet that I can test it on

**Comment by Jubeki** [comment]
I am trying to make it work, but I didn't get it running. Has some resolve errors with a path. But I dont know where the problem lies.

I wanted to mark this pr as draft but seem to forgotten it.

(Cant seem to find the mark as draft option eight now)

**Comment by BALOTIAS** [comment]
It would be great if you could update it to support laravel-mix 6+. I can't upgrade my project to webpack 5 because of this, since laravel-mix 5 doesn't support webpack 5.

This might be helpful for you:

```bash
[webpack-cli] ReferenceError: File is not defined
    at Mjml.register (/CENSORED/node_modules/laravel-mix-mjml/index.js:47:9)
    at Object.components.<computed> [as mjml] (/CENSORED/node_modules/laravel-mix/src/components/ComponentRegistrar.js:133:53)
    at Object.<anonymous> (/CENSORED/webpack.mix.js:15:5)
    at Module._compile (/CENSORED/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (/CENSORED/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports (/CENSORED/node_modules/laravel-mix/setup/webpack.config.js:4:5)
```

It seems like `File` can't be referenced. Hopefully this helps you to update the package! :))

**Comment by Jubeki** [comment]
@stidges I made it work with one of my projects. But I am not sure if it would be still working with LaravelMix 4 and 5. Since LaravelMix v6 uses Webpack5.

@BALOTIAS can you check if your project compiles with these changes?

**Comment by BALOTIAS** [comment]
I just tried it out and it seems that there is now another issue:

```
[webpack-cli] TypeError: Cannot read property 'replace' of undefined
    at _default (/CENSORED/node_modules/mjml-core/lib/helpers/minifyOutlookConditionnals.js:9:9)
    at mjml2html (/CENSORED/node_modules/mjml-core/lib/index.js:363:53)
    at /CENSORED/node_modules/laravel-mix-mjml/plugin.js:28:34
    at Array.forEach (<anonymous>)
    at /CENSORED/node_modules/laravel-mix-mjml/plugin.js:21:28
    at _next0 (eval at create (/CENSORED/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/CENSORED/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at /CENSORED/node_modules/laravel-mix/src/webpackPlugins/ManifestPlugin.js:14:13
    at Hook.eval [as callAsync] (eval at create (/CENSORED/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/CENSORED/node_modules/tapable/lib/Hook.js:18:14)

```

I tried to debug it a bit, but I couldn't really find anything that might be helpful. It reads the file correctly and the mjmlOptions are correct @ plugin.js:28:34

Tested it with laravel-mix 6.0.10 & webpack 5.17.0

Here is my webpack.mix.js:

```
const mix = require('laravel-mix');
require('laravel-mix-mjml');

mix.disableNotifications();
mix.mjml(
    'resources/views/mails/mjml/templates',
    'resources/views/mails/mjml/output',
    {
        minify: true,
        beautify: false,
    }
);
```

We literally use laravel-mix just because of this, btw awesome, plugin. We have another custom webpack config for everything else.

**Comment by Jubeki** [comment]
This seems to be a problem with Mjml:

If you try to compile a component which you then include into an Mjml file. it can't finde the tag mj-body. This results in the compiling error. If you only compile the layouts with a mj-body tag you should get no error.

Should we try to catch this error and then do something? Or leave it as is?

**Comment by Jubeki** [comment]
An example configuration for you would be:

```node
const mix = require('laravel-mix');
require('laravel-mix-mjml');

mix.disableNotifications();
mix.mjml(
    'resources/views/mails/mjml/templates/*.mjml', // Only compile files in this folder
    'resources/views/mails/mjml/output',
    {
        minify: true,
        beautify: false,
    }
);
```

And then move all components to a subdirectory for example to `resources/views/mails/mjml/templates/components`

**Comment by stidges** [comment]
@Jubeki Thanks for working on this! I'll test this out and then release v3 later :)

**Comment by BALOTIAS** [comment]
@Jubeki thanks for pointing this out! I'll check it out on monday :))

**Comment by Jubeki** [comment]
@stidges Thanks for the fast release and your additional commits.

For future reference, do you mind telling me what you added later on?
- tests and GitHub actions
- run on compilation instead on emit hook

**Comment by stidges** [comment]
@Jubeki Sure! I assume you mean what the reasoning is for adding those changes?

**Comment by BALOTIAS** [comment]
@Jubeki I've just tested it out and it works now like you mentioned! 

Might be helpful to mention this in the readme, that only the mjml files with a mj-body will be compiled @stidges :))

**Pull request merged**
